openebs/zfs-localpv

README.md
updating the README with scheduling, topology and other inforamtions.
=> chore(doc): updating readme with latest details

README.md, deploy/sample/zfspvcr.yaml, pkg/apis/openebs.io/core/v1alpha1/zfsvolume.go
=> fix(bug): fixed a typo for thinprovision json name.

.travis.yml, buildscripts/travis-build.sh
=> test(zfspv): making test cases to run on forked repo

README.md
=> chor(doc): adding roadmap in the README

CODE_OF_CONDUCT.md, GOVERNANCE.md, MAINTAINERS
=> chore(doc): making zfs-localpv repository CNCF compatible

README.md
=> chore(doc): adding badges for the ZFSPV repository

CONTRIBUTING.md, docs/developer-setup.md, docs/faq.md
=> chore(doc): adding contributing and faq doc

CHANGELOG.md
=> chore(doc): adding v0.3 changelog in the repo

docs/prometheus-monitoring.md
adding list of zfs metrics exposed by prometheus in the prometheus setup doc.
=> chore(metrics): adding list of zfs metrics exposed by prometheus

CHANGELOG.md
=> chore(doc): adding v0.4 changelog in the repo

README.md
=> chore(doc): updating readme with snapshot and clone details

pkg/driver/controller.go, pkg/zfs/zfs_util.go
Cherry-pick PR in v0.5.x https://github.com/openebs/zfs-localpv/pull/57
=> fix(clone): setting properties on the clone volume

CHANGELOG.md
=> chore(changelog): adding v0.5-RC1 changelog

README.md
=> chore(readme): adding e2e project link in README

buildscripts/zfs-driver/Dockerfile
*Addresses GLIBC incompatability
Probably fixes #67
=> Upgrade the base ubuntu package for ZFS plugin

upgrade/README.md
- Added steps to perform upgrade for refactoring the CRDs in readme file
=> chore(doc): Added readme file for upgrade scripts of refactoring CRDs

CHANGELOG.md
=> chore(changelog): adding v0.6-RC1 changelog

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> feat(yaml): adding 0.6.0 tag to the v0.6.x deployment yaml

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> feat(yaml): update the v0.6.x yaml to the latest 0.6.1 tag

deploy/zfs-operator.yaml
=> feat(yaml): update the v0.4.x yaml to the latest 0.4.1 tag

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml, upgrade/README.md, upgrade/cleanup.sh, upgrade/upgrade.sh
cherri pick PR to v0.6.x branch :-  https://github.com/openebs/zfs-localpv/pull/83 and https://github.com/openebs/zfs-localpv/pull/85.
=> cherry pick PR to avoid volumeattachment to v0.6.x branch

upgrade/README.md
Signed-off-by: Aman Gupta aman.gupta@mayadata.io
- Fixed the formatting in the upgrade readme file
=> fix(doc , format): Fixed the formatting of ReadME file for upgrade

README.md, docs/raw-block-volume.md, upgrade/README.md
also added detailed upgrade steps.
updates the doc with the latest details
**Checklist:**
=> chore(doc): adding raw block volume details in README

README.md
- Fixed the link to the raw-block-volume docs
=> fix(README): Fix the link in README file to the raw-block-volume.md file

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> fix(operator): updating v0.7.x operator with the image tag

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> fix(zfspv): changing image pull policy to IfNotPresent

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
cherry-pick https://github.com/openebs/zfs-localpv/pull/124 to the v0.7.x  banch.
=> fix(zfspv): changing image pull policy to IfNotPresent 

changelogs/unreleased/133-Icedroid
=> adding missing changelog from the contributer

deploy/operators/centos7/zfs-operator.yaml, deploy/operators/centos8/zfs-operator.yaml, deploy/yamls/centos7/zfs-driver.yaml, deploy/yamls/centos8/zfs-driver.yaml, deploy/yamls/ubuntu/zfs-driver.yaml, deploy/zfs-operator.yaml
=> feat(yaml): updating v0.8.0 operator yaml to use 0.8.0 image tag

CHANGELOG.md
=> chore(changelog): fixing link in the changelog

deploy/operators/centos7/zfs-operator.yaml, deploy/operators/centos8/zfs-operator.yaml, deploy/yamls/centos7/zfs-driver.yaml, deploy/yamls/centos8/zfs-driver.yaml, deploy/yamls/ubuntu/zfs-driver.yaml, deploy/zfs-operator.yaml
This reverts commit 2c11af5362285c034ea27d72a5abda078364291f. Accidentally merged this
change in the master branch.
=> feat(yaml): updating master operator yaml to use ci image tag

README.md
- Update the project status as beta in ReadME file
=> chore(readme): Update the project status to beta in readme

README.md, docs/resize.md
adding btrfs filesystem in the doc
**Checklist:**
=> chore(doc): adding btrfs filesystem in the doc

README.md
- This PR updates the readme for application-consistent snapshot.
- We should always scale down the application before taking the application consistent snapshot.
=> chore(readme): updating the readme for application-consistent snapshot

deploy/operators/centos7/zfs-operator.yaml, deploy/operators/centos8/zfs-operator.yaml, deploy/yamls/centos7/zfs-driver.yaml, deploy/yamls/centos8/zfs-driver.yaml, deploy/yamls/ubuntu/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating 0.9.0 image tag in the deployment yaml

README.md, docs/features.md
updating readme with the supported features for each k8s version, also updated the setup doc with ZPOOL setup information.
**Checklist:**
=> chore(doc): adding supported features doc for each k8s version

README.md, docs/faq.md
=> chore(doc): adding volume capacity roundoff details in readme

deploy/operators/centos7/zfs-operator.yaml, deploy/operators/centos8/zfs-operator.yaml, deploy/yamls/centos7/zfs-driver.yaml, deploy/yamls/centos8/zfs-driver.yaml, deploy/yamls/ubuntu/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): changing v0.9.x branch's image tag to 0.9.1

deploy/operators/centos7/zfs-operator.yaml, deploy/operators/centos8/zfs-operator.yaml, deploy/yamls/centos7/zfs-driver.yaml, deploy/yamls/centos8/zfs-driver.yaml, deploy/yamls/ubuntu/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): changing v0.9.x branch's image tag to 0.9.2

.travis.yml, changelogs/unreleased/201-pawanpraka1
=> fix(build): update go version to 1.14.7

README.md, deploy/sample/minio.yaml, docs/backup-restore.md, docs/features.md
fixes : https://github.com/openebs/velero-plugin/issues/112
adding docs for backup and restore
**Checklist:**
=> chore(doc): adding docs for backup and restore

deploy/yamls/ubuntu/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating v1.0.x branch with the 1.0.0 image tag

README.md
=> docs(data engine):add go report card badge for ZFS-LocalPV #222

docs/backup-restore.md
=> chore(doc): updating the doc with the incremental backup details

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating v1.0.x branch with v1.0.1 release tag

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
Cherry-pick PR to v1.1.x branch
=> chore(yaml): changing the zfs-driver images to multi-arch docker hub images (#237)

.github/workflows/build.yml, .github/workflows/release.yml, Makefile, buildscripts/zfs-driver/zfs-driver.Dockerfile
- pass RELEASE_TAG and BRANCH as build arguments to buildkit container
- replace deprecated methods in github actions workflow
**Checklist:**
=> chore(build): fix build script and github actions

deploy/yamls/kustomization.yaml, deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating the 1.1.x branch yaml with the release images

pkg/driver/agent.go, pkg/mount/mount_utils.go, pkg/xfs/xfs_util.go, pkg/zfs/mount.go, pkg/zfs/zfs_util.go
move xfs and mount code out of zfs package
**Checklist:**
=> chore(refactor): move xfs and mount code out of zfs package

docs/backup-restore.md
=> chore(doc): update restore doc with node mapping details

README.md
- Fix the kustomization yaml file path in readme
=> fix(doc): fixed the kustomization yaml file path in readme

README.md
fixes: https://github.com/openebs/zfs-localpv/issues/235 https://github.com/openebs/zfs-localpv/issues/112
=> chore(doc): adding installation instruction for microk8s

README.md, docs/clone.md, docs/snapshot.md
=> refactor(readme): refactoring readme

deploy/yamls/kustomization.yaml, deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating 1.2.x branch with the image tag

.github/workflows/build.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, changelogs/unreleased/260-pawanpraka1, pkg/zfs/mount.go
Cherry-pick https://github.com/openebs/zfs-localpv/pull/260 to the v1.2.x branch.
=> fix(mount): fixing idempotency check for the mount path

deploy/yamls/kustomization.yaml, deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating 1.2.x branch with the 1.2.1 image tag

docs/backup-restore.md
**What this PR does?**
- This PR updates backup and restore doc with use of s3-buckets for storing backups on cloud.
=> chore(doc): Update backup_restore doc with s3-bucket use

_config.yaml, index.md
This PR adds the config and index.md for helm repo.
**Checklist:**
=> feat(gh-pages): add github page content for zfs localpv helm charts

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
Update zfs localpv helm charts to the latest stable release 1.3.0
- update chart version
- update README
- update values.yaml
=> [stable/zfs-localpv]: update zfs-localpv charts to 1.3.0 release

deploy/yamls/kustomization.yaml, deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating 1.3.x branch yaml with the image tag

deploy/yamls/kustomization.yaml, deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> chore(yaml): updating the branch yaml with 1.4.0 image tag

deploy/yamls/zfsbackup-crd.yaml, deploy/yamls/zfsrestore-crd.yaml, deploy/yamls/zfssnapshot-crd.yaml, deploy/yamls/zfsvolume-crd.yaml, deploy/zfs-operator.yaml
Autogen description is not correct, fixing it.
=> chore(yaml): fixing autogen yaml description

README.md
- This PR updates the minimum requirement k8s version for zfs-localpv driver
=> chore(readme): update the minimum required k8s version for zfs-localpv driver

README.md
`k0s`'s alternate `/var/lib/kubelet` requires a change to the operator YAML,
Add a note about `k0s`'s required `/var/lib/kubelet` change, similar to `microk8s`.
No
**Checklist:**
=> docs(localpv): Add note about k0s use of custom kubelet directory

README.md, docs/storageclasses.md
- Update the docs/Readme with zfs-driver scheduler informations
=> chore(doc): Updated the readme/docs with zfs-driver scheduler information

deploy/helm/charts/Chart.yaml, deploy/helm/charts/values.yaml
This Pr updates the helm charts for 1.6.0 release
**Checklist:**
=> [stable/zfs-localpv]: update charts to 1.6.0

deploy/helm/charts/Chart.yaml, deploy/helm/charts/crds/zfsbackup.yaml, deploy/helm/charts/crds/zfsrestore.yaml, deploy/helm/charts/crds/zfssnapshot.yaml, deploy/helm/charts/crds/zfsvolume.yaml
This Pr updates the helm charts with the latest crds.
**Checklist:**
=> fix(helm): update the crds in helm charts

docs/import-existing-volume.md
=> chore(doc): update the import-existing-volume doc with finalizer info

.github/workflows/release-charts.yml, Makefile, buildscripts/generate-manifests.sh, deploy/helm/charts/Chart.yaml
- add make rules to copy auto generated CRDs
- add a step in chart release workflow to commit autogenerated CRDs
=> chore(crd): add rule to copy auto generated CRDs

pkg/driver/agent.go, pkg/driver/controller.go, pkg/driver/driver.go, pkg/driver/grpc.go, pkg/zfs/volume.go, pkg/zfs/zfs_util.go, tests/suite_test.go
Signed-off-by: Rahul Grover <rahulgrover99@gmail.com>
Removes many of the lining warnings. 
Removes unused variables, functions, and imports. 
No
NA
No
=> (bugbash) refact(zfspv) Removes unused import, variables and functions.

pkg/driver/agent.go, pkg/driver/controller.go, pkg/version/version.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
Final Quest Challenge :)
=> (bugsbash) handle errors

pkg/driver/grpc.go, pkg/usage/versionset.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
Related to bugsbash
=> refactor(fix unhandled errors)

.github/workflows/release.yml
fixes: https://github.com/openebs/zfs-localpv/issues/328
automatically update the operator yaml with the image tag at the release time.
=> feat(action): autogenerate the operator yaml with the image tag

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
fixes: https://github.com/openebs/zfs-localpv/issues/328
=> chore(yaml): updating 1.5.x operator yaml with the image tag

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
fixes: https://github.com/openebs/zfs-localpv/issues/328
=> chore(yaml): updating 1.6.x operator yaml with the image tag

.github/workflows/release-charts.yml, .github/workflows/release.yml
=> fix(action): updating signoff to openebs.io

deploy/helm/charts/Chart.yaml, deploy/helm/charts/crds/zfsvolume.yaml, deploy/helm/charts/templates/zfs-node.yaml, deploy/helm/charts/values.yaml
This Pr updates the helm charts for 1.6.0 release
**Checklist:**
=> [stable/zfs-localpv]: update charts to 1.7.0

pkg/zfs/mount.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Change file permissions!!
=> Change file permissions to fix gosec G301 Error

.github/workflows/release.yml
Cherry-Picking the PR https://github.com/openebs/zfs-localpv/pull/340 to v1.8.x branch.
=> fix(version): auto update the version label in the operator yaml (#340)

.github/workflows/release.yml
cherry-pick #342 
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
=> cherry-pick(workflow): replace ci tag with regex in release workflow 

.github/workflows/release.yml
- replace ci tag with regex in sed
- use github actions user to commit changes instead of GITHUB_ACTOR
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
=> chore(workflow): replace ci tag with regex in release workflow

Adopters.md
- This PR adds zfs-localpv adopter list
=> chore(doc): add adopters.md file

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md
This PR updates the helm README with the latest config values.
**Checklist:**
=> chore(helm): update config default values in README

README.md, e2e-tests/experiments/functional/zfspv-custom-topology/app_gen_immediate.sh, e2e-tests/experiments/functional/zfspv-custom-topology/app_gen_wfc.sh
- This PR updates the slack openebs channel community link.
=> Update the readme with slack link to openebs channel

README.md
fixes #354 
This addes an example rancher operator yaml file.
No, this is merely an example for documentation.
The rancher operator file in question merely changes a few paths, but I would like someone to verify that I changed the correct paths.
**Checklist:**
=> doc(example): fixes #354 by adding a RancherOS example

.github/workflows/chart-lint-test.yml, deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
Updated Chart.yaml values.yaml and README with 2.11.0 release
=>  [stable/zfs-localpv]: update charts to 1.9.0

deploy/yamls/kustomization.yaml
=> chore(yaml): add zfsnode-crd.yml to kustomize resources

deploy/helm/charts/Chart.yaml, deploy/helm/charts/templates/_helpers.tpl, deploy/helm/charts/templates/priority-class.yaml, deploy/helm/charts/values.yaml
PR add prioirityClass template and update the zfslocalpv StatefulSet and Daemonsets to use these custom priorityclass instead of using the k8s inbuilt one.
No
**Checklist:**
=> [stable/zfs]: add custom priorityclass template for zfs charts

e2e-tests/hack/crds.yaml, e2e-tests/hack/rbac.yaml
- Update zfs  e2e-crds apiversion to v1
=> refact(e2e-crd): update zfs e2e-crds apiversion to v1

e2e-tests/hack/e2e-result.j2
- fix typo in kind filed of e2e-result yaml file
=> fix(typo): fix typo in kind field of E2e-result cr yaml file

deploy/yamls/zfs-driver.yaml, deploy/zfs-operator.yaml
=> refact(operator): update zfs operator with custom priorityclass (#367)

e2e-tests/hack/crds.yaml, e2e-tests/hack/e2e-result.j2, e2e-tests/hack/rbac.yaml
Signed-off-by: w3aman aman.gupta@mayadata.io
- Update zfs e2e-crds apiversion to v1
=> refact(e2e-crds): update zfs e2e-crds apiversion to v1

e2e-tests/chaoslib/service_failure/service_chaos.yml, e2e-tests/experiments/functional/backup_and_restore/setup_dependency.yml, e2e-tests/experiments/infra-chaos/node_failure/run_e2e_test.yml, e2e-tests/experiments/infra-chaos/node_failure/test.yml, e2e-tests/experiments/infra-chaos/node_failure/test_vars.yml
- Signed-off-by: w3aman aman.gupta@mayadata.io
cherry pick: #366 #362
=> refact(e2e): load key's passphrase in dataset after node-power-failure test case

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
Updates heml Chart.yaml values.yaml and README with 1.9.1 release
**Checklist:**
=> [stable/zfs-localpv]: update charts to 1.9.1

deploy/helm/charts/Chart.yaml, deploy/helm/charts/templates/zfs-contoller.yaml, deploy/helm/charts/templates/zfs-node.yaml
fixes the helm templates of CSI driver controller and node to include the custom priorityclass changes
=> fix(templates): update csi driver templates with priorityclass

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/templates/csidriver.yaml, deploy/helm/charts/templates/zfs-contoller.yaml, deploy/helm/charts/values.yaml
- Update the CSI driver sidecars version as below:
* CSI Provisioner:
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
* CSI Resizer:
k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
* CSI Node Driver Registrar
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
- Add `storegeCapacity: true` parameter in CSIDriver resource
Refer: #374 
=> chore(helm): bump csi sidecars and add storagecapacity in csidriver

e2e-tests/experiments/upgrade-zfs-localpv/test.yml
=> chore(cherry-pick): Cherry-pick for PR #379 into v1.9.x

.github/workflows/build.yml, .github/workflows/release.yml
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
This adds Github Actions CI instructions to push built images to GHCR image registry.
Adds GHCR login and registry prefix to images.
=> chore(ci): add GHCR build and push steps to build.yml and release.yml

.github/workflows/build.yml, .github/workflows/release.yml
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
Cherry-picks the following into v1.9.x branch:
1. #381
=> Cherry-pick #381

.github/workflows/build.yml, .github/workflows/chart-lint-test.yml, .github/workflows/pull_request.yml, .github/workflows/release-charts.yml, Adopters.md, CONTRIBUTING.md, GOVERNANCE.md, README.md, RELEASE.md, buildscripts/push, ct.yaml, deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, docs/backup-restore.md, docs/developer-setup-examples.md, docs/developer-setup.md, docs/faq.md, docs/grafana-dashboard.md, e2e-tests/experiments/upgrade-zfs-localpv/README.md, e2e-tests/experiments/upgrade-zfs-localpv/run_e2e_test.yml, e2e-tests/experiments/upgrade-zfs-localpv/test.yml, e2e-tests/experiments/zfs-localpv-provisioner/run_e2e_test.yml
This PR is required to mark develop branch as a default branch
This PR does following changes:
- Updates branch reference from master to develop(HEAD) in README.md files
- Updates build branch to 'develop' in github workflow
**Checklist:**
=> chore(ci): updating branch reference from master to develop(HEAD)

.github/workflows/build.yml, .github/workflows/chart-lint-test.yml, .github/workflows/pull_request.yml, .github/workflows/release-charts.yml, Adopters.md, CONTRIBUTING.md, GOVERNANCE.md, README.md, RELEASE.md, buildscripts/push, ct.yaml, deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, docs/backup-restore.md, docs/developer-setup-examples.md, docs/developer-setup.md, docs/faq.md, docs/grafana-dashboard.md, e2e-tests/experiments/upgrade-zfs-localpv/README.md, e2e-tests/experiments/upgrade-zfs-localpv/run_e2e_test.yml, e2e-tests/experiments/upgrade-zfs-localpv/test.yml, e2e-tests/experiments/zfs-localpv-provisioner/run_e2e_test.yml
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
=> chore(ci): updating branch reference from master to develop(HEAD) (#384)
