- README.md
> chore(doc): adding README for ZFSPV

- README.md
- buildscripts/zfs-driver/Dockerfile
- deploy/zfs-operator.yaml
The ZFS 0.8 has dependency on libcrypto.so.1.1 which in turn
requires GLIBC_2.25 supported by the system. Changed the docker
image to 18:04 as 16:04 has glibc version 2.23.
Also updated the README with the supported system details.
> bug(zfspv): not able to deploy on rancher with ZFS 0.8.

- README.md
updating README with volume property usage.
> chore(doc): updating README with volume property usage

- deploy/sample/fio.yaml
- deploy/sample/percona.yaml
- deploy/zfs-operator.yaml
- pkg/apis/openebs.io/core/v1alpha1/zfsvolume.go
- pkg/builder/build.go
- pkg/driver/controller.go
- pkg/zfs/zfs_util.go
Also adding support to inherit the properties from ZPOOL
which are not listed in the storage class, ZFS driver will
not pass default values while creating the volume. Those
properties will be inherited from the ZPOOL.
we can use the encryption option in storage class 
```
metadata:
parameters:
blocksize: "4k"
compression: "on"
dedup: "on"
thinprovision: "yes"
encryption: "on"
keyformat: "raw"
keylocation: "file:///home/keys/key"
provisioner: openebs.io/zfs
```
Just a note, the key file should be mounted inside the node-agent container so that we can use that file while provisioning the volume. keyformat can be raw, hex or passphrase.
Signed-off-by: Pawan …
> feat(ZFSPV): adding encryption in ZFSVolume CR

- cmd/controller/controller.go
- deploy/sample/fio.yaml
- deploy/sample/percona.yaml
- deploy/zfs-operator.yaml
- pkg/builder/build.go
- pkg/driver/agent.go
- pkg/driver/controller.go
- pkg/response/create.go
- pkg/zfs/mount.go
- pkg/zfs/volume.go
- pkg/zfs/zfs_util.go
We can provide the topology in storage class where the zfs pools are setup
```yaml
metadata:
parameters:
blocksize: "4k"
compression: "on"
dedup: "on"
thinprovision: "yes"
provisioner: zfs-localpv
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
- key: kubernetes.io/hostname
values:
- gke-zfspv-pawan-default-pool-c8929518-cgd4
- gke-zfspv-pawan-default-pool-c8929518-dxzc
```
The scheduler will take care of scheduling the application on the appropriate node.
> adding topology support for zfspv

- cmd/main.go
- deploy/sample/fio.yaml
- deploy/sample/percona.yaml
- deploy/zfs-operator.yaml
- pkg/driver/controller.go
- pkg/driver/scheduler.go
- pkg/zfs/volume.go
The scheduler will go through all the nodes as per
topology information and it will pick the node which has less
volume provisioned in the given pool.
lets say there are 2 nodes node1 and node2 with below pool configuration :-
```
node1
|
|-----> pool1
|         |
|         |------> pvc1
|         |------> pvc2
|-----> pool2
|------> pvc3
node2
|
|-----> pool1
|         |
|         |------> pvc4
|-----> pool2
|------> pvc5
|------> pvc6
```
So if application is using pool1 as shown in the below storage class, then ZFS driver will schedule it on node2 as it has one volume as compared to node1 which has 2 volumes in pool1.
```yaml
metadata:
parameters:
blocksize: "4k"
compression: "on" …
```
> feat(ZFSPV): scheduler for ZFSPV

- buildscripts/zfs-driver/Dockerfile
- deploy/sample/mongo-statefulset.yaml
adding xfs filesystem support for zfs-localpv also added mongodb stateful set sample yaml. 
> feat(ZFSPV): adding xfs filesystem support for zfs-localpv

- .travis.yml
> remove unnecessary deploy operation from travis

- README.md
- deploy/sample/mongo-statefulset.yaml
- deploy/sample/zfspvcr.yaml
updating sample ZFSVolume CR, also changed  the API version for mongo-statefulset.yaml to make it run on kubernetes 1.16 and updated few minor details in README to make it consistent.
> fix(doc): updating sample ZFSVolume CR

- README.md
fix scheduling algorithm doc and explain how the scheduling is done currently. Also included the steps to make use of kubernetes scheduler instead of the scheduler in zfs-localpv
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
> chore(README): fix scheduling algorithm doc

- cmd/controller/controller.go
- deploy/sample/fio.yaml
- deploy/sample/mongo-statefulset.yaml
- deploy/sample/percona.yaml
- deploy/sample/zfspvcr.yaml
- deploy/zfs-operator.yaml
- pkg/apis/openebs.io/core/v1alpha1/zfsvolume.go
- pkg/builder/build.go
- pkg/driver/agent.go
- pkg/driver/controller.go
- pkg/driver/scheduler.go
- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
Application can now create a storageclass to create zfs filesystem
metadata:
parameters:
recordsize: "4k"
fstype: "zfs"
ZFSPV was supporting ext2/3/4 and xfs filesystem only which
adds one extra filesystem layer on top of ZFS filesystem. So now
we can directly write to the ZFS filesystem and get the optimal performance
by directly creating ZFS filesystem for storage.
Renamed the blocksize to volblocksize, which will be used for creating the zvols and if it is provided for dataset, it will be ignored and recordsize will be used for creating the zfs datasets, if it is provided for zvol, it will be ignored
Also added support to change the …
> feat(ZFSPV): adding support for applications to create "zfs" flesystem

- deploy/sample/mongo-statefulset.yaml
- deploy/sample/percona.yaml
- deploy/sample/zfspvcr.yaml
As the selector is needed in the latest kubetnetes cluster
Also updated zfs volume custom resource and renamed few
fields of percona application.
> fix(yaml): fixing mongo yaml

- cmd/main.go
- pkg/builder/build.go
- pkg/driver/agent.go
- pkg/driver/scheduler.go
- pkg/mgmt/builder.go
- pkg/mgmt/mgmt.go
- pkg/mgmt/start.go
as it does the management task also corrected few logs
and renamed zvol to zfs(as we support zvol and dataset both)
> refactor(zfspv): renamed watcher to mgmt package

- deploy/zfs-operator.yaml
to make it not pull the image all the time. Also, it needed
so that while doing integration test, it uses the local image
we just build, instead of fetching the image from the dockerhub or quay
so that we can run ci on the locally built image.
> fix(zfspv): changing image pull policy to IfNotPresent

- CHANGELOG.md
> chore(doc): adding changelog in the repo

- .travis.yml
- ci/ci-test.sh
- pkg/mgmt/mgmt.go
- pkg/zfs/zfs_util.go
- tests/provision_test.go
- tests/suite_test.go
- tests/utils.go
> test(zfspv): adding test cases to verify zfs property update

- pkg/driver/agent.go
- pkg/zfs/mount.go
```
$ curl localhost:10255/metrics | grep volume_stats
kubelet_volume_stats_available_bytes{namespace="default",persistentvolumeclaim="csi-zfspv"} 3.053129728e+09
kubelet_volume_stats_available_bytes{namespace="default",persistentvolumeclaim="csi-zfspv1"} 4.294836224e+09
kubelet_volume_stats_capacity_bytes{namespace="default",persistentvolumeclaim="csi-zfspv"} 4.160421888e+09
kubelet_volume_stats_capacity_bytes{namespace="default",persistentvolumeclaim="csi-zfspv1"} 4.294967296e+09
kubelet_volume_stats_inodes{namespace="default",persistentvolumeclaim="csi-zfspv"} 262144
kubelet_volume_stats_inodes{namespace="default",persistentvolumeclaim="csi-zfspv1"} 8.388422e+06
kubelet_volume_stats_inodes_free{namespace="default",persistentvolumeclaim="csi-zfspv"} 262132 …
```
> feat(stats): adding volume stats

- deploy/zfs-operator.yaml
- docs/faq.md
We can have more than one controller in the system, but only one will
be the master and others will be slave. Once master is down, one of the slave will
take over via lease mechanism and start provisioning/deprovisioning the volumes.
controller pod will have anti-affinity so that no two pods get scheduled on the same node. Also keeping the default replica to 1, if HA feature is required, we can change replica count to 2(or more).
> feat(HA): adding support to have controller in HA

- deploy/sample/alertmanager-service.yaml
- deploy/sample/prometheus-alert.rules
- deploy/sample/prometheus-service.yaml
- docs/prometheus-monitoring.md
This PR has a sample rule to monitor the volume space utilization, and once available space is less than 10%, it will start firing the alert.
```
100 * kubelet_volume_stats_available_bytes{job="kubelet"}
/
kubelet_volume_stats_capacity_bytes{job="kubelet"}
< 10
```
Just update the yaml with the desired alert rule and apply the yaml. You will start getting the alert as per set rule.
> feat(alert): adding sample prometheus rules for ZFSPV

- README.md
- Resolve the typo in parameter `volblocksize` in storage class yaml.
> fix(doc): Resolving the typo error in README doc

- pkg/zfs/zfs_util.go
With "zfs destroy -R" we will delete snapshot and clones also. We should
not use that for deleting the volumes.
> fix(zfspv): do not destroy the dataset with -R option

- deploy/zfs-operator.yaml
changes fix the zfs operator yaml to use 1.5.0 csi-provisioner image to support volumesnapshot as datasource type to create clone persistent volumes.
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
> fix(operator): update provisioner image to support snapshot datasource

- docs/e2e-pipeline.md
Signed-off-by: Aman Gupta aman.gupta@mayadata.io
- List of the test cases which are running in e2e-pipelines and the test cases which are manually tested.
- Manually tested cases are in plans to add in future.
> add(doc): Added the list of automated and manual e2e test cases specific to zfs-localpv 

- deploy/zfs-operator.yaml
- pkg/driver/agent.go
- pkg/driver/controller.go
- pkg/response/resize.go
- pkg/zfs/resize.go
- pkg/zfs/volume.go
- pkg/zfs/zfs_util.go
We can resize the volume by updating the PVC yaml to
the desired size and apply it. The ZFS Driver will take care
of updating the quota in case of dataset. If we are using a
Zvol and have mounted it as ext4 or xfs filesystem, the driver will take
care of expanding the volume via reize2fs/xfs_growfs binaries.
For resize, storageclass that provisions the pvc must support resize. We should have allowVolumeExpansion as true in storageclass
```yaml
metadata:
parameters:
```
> feat(resize): adding Online volume expansion support for ZFSPV

- tests/provision_test.go
- tests/suite_test.go
- tests/utils.go
Adding test case to verify resize. Here we are creating a PVC and deploying an application using that PVC and then resizing the PVC and waiting for it be resized.
> feat(resize): adding BDD test for Online volume expansion

- README.md
- docs/resize.md
updating the readme with the resize details.
> chore(doc): adding resize details in README

- pkg/driver/controller.go
- pkg/zfs/zfs_util.go
fixes https://github.com/openebs/zfs-localpv/issues/55.
When we clone the zvol, it inherits volsize and block size from the snapshot from which this clone is created. This is not true for datasets, we have to set all the properties while creating the clone. Also, properties like compression, dedup will not be set on the cloned volume for both zvol and dataset. Here I am setting all the prperties for zvol and dataset while creating the clone volume.
> fix(clone): setting properties on the clone volume

- deploy/zfs-operator.yaml
Now we have started creating a branch for each release,
it is better that each branch's operator file points
to the right release tag instead of ci. After this we
can directly apply the operator files from each branch
to upgrade to the desired release version. This will
not be needed once ZFSPV is the part of openebs installer.
> feat(image): updating operator file with v0.4 image tag

- deploy/zfs-operator.yaml
Now we have started creating a branch for each release,
it is better that each branch's operator file points
to the right release tag instead of ci. After this we
can directly apply the operator files from each branch
to upgrade to the desired release version. This will
not be needed once ZFSPV is the part of openebs installer.
> feat(image): updating operator file with v0.5 image tag

- pkg/zfs/zfs_util.go
fixes : https://github.com/openebs/zfs-localpv/issues/56
for mounting the cloned volume for xfs, a new UUID has to be generated.
We are generating a new UUID for the cloned volumes which are formatted
as xfs using xfs_admin command.
> fix(xfs): fixing xfs duplicate uuid for cloned volumes

- pkg/zfs/xfs_util.go
- pkg/zfs/zfs_util.go
xfs_admin command to generate the new UUID for the cloned
volume fails without returning error if there is log available
in the filesystem :
ERROR: The filesystem has valuable metadata changes in a log which needs to
be replayed.  Mount the filesystem to replay the log, and unmount it before
re-running xfs_admin.  If you are unable to mount the filesystem, then use
the xfs_repair -L option to destroy the log and attempt a repair.
Note that destroying the log may cause corruption -- please attempt a mount
of the filesystem before doing this.
No UUID will be generated in this case and application can not mount the volume.
Here mounting the filesystem to the temp location with "nouuid" mount option first
so that it can replay the logs first and system is in clean state and then unmount it …
> fix(xfs): clearing the xfs log before generating UUID

- ci/ci-test.sh
- tests/suite_test.go
- tests/utils.go
We are comparing the desired size to the wrong field
because of that resize test is not executing correctly
and sometimes causing test case failure in travis.
The update call is failing sometimes while executing the zfs
property update test cases as for resize also the object
is getting modified. The test case will fail when object updation
happens between volume GET and UPDATE call while performing
zfs property update test case to set various properties on
ZFSVolume resource.
> fix(test): fixing resize flaky test case

- upgrade/cleanup.sh
- upgrade/crd.yaml
- upgrade/upgrade.sh
steps to upgrade :-
1. apply the new CRD
```
$ kubectl apply -f upgrade/crd.yaml
customresourcedefinition.apiextensions.k8s.io/zfsvolumes.zfs.openebs.io created
customresourcedefinition.apiextensions.k8s.io/zfssnapshots.zfs.openebs.io created
```
2. run upgrade.sh
```
$ sh upgrade/upgrade.sh
zfsvolume.zfs.openebs.io/pvc-086a8608-9057-42df-b684-ee4ae8d35f71 created
zfsvolume.zfs.openebs.io/pvc-5286d646-c93d-4413-9707-fd95ebaae8c0 created
zfsvolume.zfs.openebs.io/pvc-74abefb8-8423-4b13-a607-7184ef088fb5 created
zfsvolume.zfs.openebs.io/pvc-82368c44-eee8-47ee-85a6-633a8023faa8 created
zfssnapshot.zfs.openebs.io/snapshot-dc61a056-f495-482b-8e6e-e7ddc4c13f47 created
zfssnapshot.zfs.openebs.io/snapshot-f9db91ea-529e-4dac-b2b8-ead045c612da created
```
3. upgrade the driver to v0.6 (tag to be …
> feat(crd): upgrade script for refactoring the CRD

- pkg/driver/agent.go
- pkg/driver/controller.go
- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
There can be cases where openebs namespace has been accidentally deleted. If that happens, the volume CRs deletion will be triggered. Volume CR deletion will trigger dataset deletion process. Prior to the actual deletion of the data, the driver will attempt to do the following:
- Unmount the dataset(not the case with zvol as it will be unmounted via NodeUnPublish) Unmounting the dataset will Set the mount="no"
- Delete the zvol or dataset
But since the volume is actively consumed by a pod, the destroy will fail, as the volume is busy. The zvols continue to operate. However with datasets, it is umounted resulting in the setting of mount="no", but then delete will fail.
Now, there are two actions that the user can take:
(a) Continue to clean-up, so that setup can be re-created
(b) Reinstall …
> feat(zfspv): handling unmounted volume .

- pkg/driver/agent.go
- pkg/driver/controller.go
- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
Cherry-pick to v0.6.x : https://github.com/openebs/zfs-localpv/pull/76
There can be cases where openebs namespace has been accidentally deleted. If that happens, the volume CRs deletion will be triggered. Volume CR deletion will trigger dataset deletion process. Prior to the actual deletion of the data, the driver will attempt to do the following:
Unmount the dataset(not the case with zvol as it will be unmounted via NodeUnPublish) Unmounting the dataset will Set the mount="no"
Delete the zvol or dataset
But since the volume is actively consumed by a pod, the destroy will fail, as the volume is busy. The zvols continue to operate. However with datasets, it is umounted resulting in the setting of mount="no", but then delete will fail.
Now, there are two actions that the user can take:
(a) …
> feat(zfspv): handling unmounted volume

- pkg/driver/controller.go
- pkg/zfs/volume.go
Now PV will have poolname/parent-dataset info in volume attributes.
It will help to identify that PV has been create in which zpool.
```
$ kubectl describe pv pvc-22d55c56-0c52-4fd5-894c-1f54c4dac5b7
Name:              pvc-22d55c56-0c52-4fd5-894c-1f54c4dac5b7
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: zfs.csi.openebs.io
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      openebs-zfspv
Status:            Bound
Claim:             default/pvcname208
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          4Gi
Node Affinity:
Required Terms:
Term 0:        kubernetes.io/hostname in [pawan-2]
Message:
Source:
Type:              CSI (a Container Storage Interface (CSI) volume source)
Driver: …
```
> feat(zfspv): adding poolname info to the PV volumeattributes

- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
fixes: https://github.com/openebs/zfs-localpv/issues/88
looks like a bug in ZFS as when you change the mountpoint property to none,
ZFS automatically umounts the file system. When we delete the pod, we get the 
unmount request for the old pod and mount request for the new pod. Unmount
is done by the driver by setting mountpoint to none and the driver assumes that
unmount has done and proceeded to delete the mountpath, but here zfs has not unmounted
the dataset
```
$ sudo zfs get all zfspv-pool/pvc-3fe69b0e-9f91-4c6e-8e5c-eb4218468765 | grep mount
zfspv-pool/pvc-3fe69b0e-9f91-4c6e-8e5c-eb4218468765  mounted               yes                                                                                                -
zfspv-pool/pvc-3fe69b0e-9f91-4c6e-8e5c-eb4218468765  mountpoint …
```
> fix(zfspv): fixing data loss in case of pod deletion

- docs/developer-setup-examples.md
Signed-off-by: Filippo Bosi <filippo.bosi@gmail.com>
The documentation to setup development environment (from an os and minikube point of view) is not very detailed. I started writing down detailed notes on how to setup an environment and pass integration tests.
> added developer environment examples

- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
- upgrade/README.md
- upgrade/cleanup.sh
- upgrade/upgrade.sh
fixes :- https://github.com/openebs/zfs-localpv/issues/79
k8s is very slow in attaching the volumes when dealing with the 
large number of volume attachment object.
(k8s issue https://github.com/kubernetes/kubernetes/issues/84169)
The volumeattachment is not required for ZFSPV, so avoid creation
of attachment object, also removed the csi-attacher container as
this is also not needed as it acts on volumeattachment object.
k8s is very slow in attaching the volumes when dealing with the 
large number of volume attachment object : 
k8s issue https://github.com/kubernetes/kubernetes/issues/84169).
Volumeattachment is a CR created just to tell the watcher of it
which is csi-attacher, that it has to call the Controller Publish/Unpublish grpc.
Which does all the tasks to attach the volumes to a …
> feat(attach): avoid creation of volumeattachment object

- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
- docs/faq.md
- pkg/client/k8s/v1alpha1/node.go
- pkg/driver/agent.go
- pkg/driver/scheduler.go
- unreleased/94-pawanpraka1
fixes :- https://github.com/openebs/zfs-localpv/issues/84
Now user can label the nodes with the required topology, the ZFSPV
driver will support all the node labels as topology keys.
We should label the nodes first and then deploy the driver to make it aware of
all the labels that node has. If we want to add labels after ZFS-LocalPV driver
has been deployed, a restart all the node agents are required so that the driver
can pick the labels and add them as supported topology keys.
Note that if storageclass is using Immediate binding mode and topology key is not mentioned then all the nodes should be labeled using same key, that means, same key should be present on all nodes, nodes can have different values for those keys. If nodes are labeled with different keys i.e.
some nodes are having …
> feat(topology): adding support for custom topology keys

- pkg/zfs/volume.go
- unreleased/101-pawanpraka1
fixes: https://github.com/openebs/zfs-localpv/issues/100
depends on :- https://github.com/openebs/zfs-localpv/pull/94
There are setups where nodename is different than the hostname.
The driver uses the nodename and tries to set the "kubernetes.io/hostname"
node label to the nodename. Which will fail if nodename is not same as
hostname. Here, changing the key to unique name so that the driver can set
that key as node label and also it can not modify/touch the existing node labels.
Now onwards, the driver will use "openebs.io/nodename" key to set the PV node affinity.
Old volumes will have "kubernetes.io/hostname" affinity, and they will also work as
after the PR https://github.com/openebs/zfs-localpv/pull/94, it supports all the node
labels as topology key and all the nodes have …
> fix(topokey): changing topology key to unique name

- deploy/sample/fio-block.yaml
- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
- pkg/driver/agent.go
- pkg/zfs/mount.go
- tests/container/container.go
- tests/provision_test.go
- tests/pvc/build.go
- tests/utils.go
- unreleased/102-pawanpraka1
Fixes: https://github.com/openebs/openebs/issues/2971
We can create a Raw Block Volume request using volumemode as block in PVC :-
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: block-claim
spec:
volumeMode: Block
storageClassName: zfspv-block
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 5Gi
```
we can use the below storageclass for RAW block volume:
```
metadata:
name: zfspv-block
parameters:
```
The driver will create a zvol for this volume and bind mount the block  device at the given path.
> feat(block): adding block volume support for ZFSPV

- Makefile
- buildscripts/push
- buildscripts/zfs-driver/Dockerfile
This PR makes the docker images configurable and removes the leading v from image tags. This is required to make the image name consistent with other openebs images
make the docker images configurable and  trim leading v from image tag.
*Does this PR require any upgrade changes?**:
NA
**Checklist:**
> refact(build): make the docker images configurable

- buildscripts/push
> refact(build):trim leading v from image tag

- docs/import-existing-volume.md
Docs for attaching an existing volume to ZFS-LocalPV
> chore(import-vol): adding steps to import existing volume to ZFS-LocalPV

- buildscripts/build.sh
if there are no changes then "git describe --tags `git rev-list --tags --max-count=1`"
may return older tag as there will be two tags referring to the same commit.
Using travis tag here to clearly differentiate the versions.
> fix(version): use the travis tag for the version

- docs/faq.md
**What this PR does?**
- Updated the faq doc for custom-topology support by adding when restarting of zfs driver node agent is must, even though restart is recommended.
> chore(doc): Updated the doc for custom-topology support

- deploy/yamls/zfsvolume-crd.yaml
- deploy/zfs-operator.yaml
- pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go
Creation time Stamp is not useful information as we already have the Age, Also volblocksize and Recordsize can not co-exist, feeling it is better to remove them(open for suggestion) as we can get the info from the storageclass.
> feat(print): removing unnecessary printer columns

- pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go
- pkg/driver/agent.go
Readonly flag does not come as mount option, it has
separate field to mention readonly flag. ZFS-LocalPV
driver should check that field and add "ro" as mountoption.
**Checklist:**
> fix(readonly): honouring readonly flag.

- CONTRIBUTING.md
improve the contrubuting document，add make format document to the contrubuting document.
> add contributing checkout list

- changelogs/unreleased/144-cruwe
- pkg/common/helpers/helpers.go
- pkg/driver/controller.go
fixes #143 -> inconsistent naming of fsType with fallback to ext4 and all datasets created as volumes
Reformulating the getter allows volumes to be created with zfs-type, which will result in a "filesystem" dataset.
I do not think so.
Without this fix, a dataset as described in #143 is created as a volume. With the fix, it is created as a dataset of type filesystem. Conersly, with type xfs, it is still created as a dataset of type volume. I imagine my testing could have been more thorough, this is what I managed to do to with the time at hand.
**Checklist:**
> fix(provisioning): make volumes with fsType=zfs datasets of type filesystem

- changelogs/unreleased/145-pawanpraka1
- pkg/driver/controller.go
- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
fixes: https://github.com/openebs/zfs-localpv/issues/130
PVC will not bound if there are wrong parameters/poolname in the storageclass,
the ZFSVolume CR will be still created and will remain in Pending State,
deletion of the PVC will delete PVC and since PVC is not bound, ZFS-LocalPV
driver will not get the delete call and will leave the ZFSVolume CR hanging there.
Reverting the behavior introduced in https://github.com/openebs/zfs-localpv/pull/121,
Now PVC will be bound but still ZFSVolume will be in Pending state until the volume is created.
Now, with the wrong parameter, the POD will be in ContainerCreating and describe of it will show that mount is failing
```
Warning …
```
> fix(pvc): fixing stale ZFSVolume CR issue when deleting pending PVC

- changelogs/unreleased/150-pawanpraka1
- deploy/operators/centos7/zfs-operator.yaml
- deploy/operators/centos8/zfs-operator.yaml
- deploy/yamls/centos7/zfs-driver.yaml
- deploy/yamls/centos8/zfs-driver.yaml
- deploy/yamls/ubuntu/zfs-driver.yaml
- deploy/zfs-operator.yaml
- pkg/driver/controller.go
- pkg/usage/googleanalytics.go
- pkg/usage/usage.go
> feat(usage): include pvc name in volume events

- changelogs/unreleased/151-pawanpraka1
- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
We can not mount the datasets to more than one path via zfs mount command, shifting to the legacy way of handling ZFS volumes where we can mount/umount the datasets via legacy mount and umount commands.
This will also add a building block for SINGLE-NODE-MULTI-WRITER Capability.
**Checklist:**
> feat(mount): moving to legacy mount

- changelogs/unreleased/161-vaniisgh
- pkg/driver/grpc.go
Fixes #136 , removes the NodeGetCapabilities & NodeGetVolumeStats logs.
Adds a loop in the logGRPC function
Locally, some tests failed, I cant seem to locate them
**Checklist:**
Signed-off-by: vaniisgh <vanisingh@live.co.uk>
> feat(zfspv): filter grpc logs to reduce the pollution

- Makefile
- changelogs/unreleased/167-vaniisgh
adds a target for lint as needed by #165
**Questions**
should the golint output be formatted before printing somehow ... ?
also i need to fix the spelling for recommendations, will do with the change-log or any additional changes :) 
**Checklist:**
> feat(zfspv) add go lint target

- changelogs/unreleased/164-pawanpraka1
- deploy/operators/centos7/zfs-operator.yaml
- deploy/operators/centos8/zfs-operator.yaml
- deploy/yamls/zfssnapshot-crd.yaml
- deploy/yamls/zfsvolume-crd.yaml
- deploy/zfs-operator.yaml
- pkg/apis/openebs.io/zfs/v1/zfsvolume.go
- pkg/builder/volbuilder/build.go
- pkg/driver/controller.go
- pkg/driver/grpc.go
- pkg/zfs/mount.go
fixes : https://github.com/openebs/zfs-localpv/issues/152
Applications who wants to share a volume can use below storageclass
to make their volumes shared by multiple pods
```yaml
metadata:
parameters:
shared: "yes"
fstype: "zfs"
```
Now the provisioned volume using this storageclass can be used by multiple pods.
Here pods have to make sure of the data consistency and have to have locking mechanism.
One thing to note here is pods will be scheduled to the node where volume is present
so that all the pods can use the same volume as they can access it locally only. 
This way …
> feat(shared): adding shared mount support ZFSPV volumes

- buildscripts/zfs-driver/Dockerfile
- changelogs/unreleased/170-pawanpraka1
fixes: https://github.com/openebs/zfs-localpv/issues/169
Now, applications can use the btrfs file system by mentioning "btrfs"
as fstype in the storageclass :-
```yaml
metadata:
parameters:
fstype: "btrfs"
```
**Checklist:**
> feat(btrfs): adding support to have btrfs filesystem for ZFS-LocalPV

- changelogs/unreleased/171-vaniisgh
- ci/ci-test.sh
Signed-off-by: vaniisgh <vanisingh@live.co.uk>
Adds functions to check if zfs-driver component pods are running in the kube-system namespace
**Any additional questions for your reviewer?** :
Should I name the pods explicitly ? 
**Checklist:**
> feat(zfspv): check pod-status in BDD test

- changelogs/172-pawanpraka1
- pkg/zfs/btrfs_util.go
- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
fixes : https://github.com/openebs/zfs-localpv/issues/169
Continuation of the PR https://github.com/openebs/zfs-localpv/pull/170
btrfs, like xfs, needs to generate a new UUID for the
cloned volumes. All the devices with the same UUID will be treated
same for btrfs.
generating the new UUID for the cloned volumes using btrfstune command.
no
**Checklist:**
> fix(btrfs): fixing duplicate UUID issue with btrfs

- buildscripts/zfs-driver/Dockerfile
- changelogs/unreleased/179-pawanpraka1
fixes : https://github.com/openebs/zfs-localpv/issues/173
We changed the ubuntu docker image to 20.04 in https://github.com/openebs/zfs-localpv/pull/170,
which has issues with formatting the zvol as xfs file system. The filesystem
formatted with xfs is not able to mount with error : "missing codepage or helper program, or other error".
Reverting back to ubuntu 19.10 to fix this issue.
**Checklist:**
> fix(zfspv): fixing mounting issue with xfs on centos

- changelogs/unreleased/184-pawanpraka1
- pkg/zfs/mount.go
- pkg/zfs/zfs_util.go
Instead of checking for the finalizer, checking for the
volume state to be ready is more intuitive before mounting it.
Also removed duplicate if statement for btrfs which was added while resolveing
the merge conflict in https://github.com/openebs/zfs-localpv/pull/175.
**Checklist:**
> fix(zfspv): mounting the volume if it is ready

- changelogs/unreleased/183-pawanpraka1
- pkg/zfs/xfs_util.go
fixes: https://github.com/openebs/zfs-localpv/issues/182
This issue is specific to xfs only, when we create a clone volume and system is taking time in creating the device.
When we create a clone volume from a xfs filesystem, ZFS-LocalPV will go ahead and generate a new UUID for the clone volumes as we need a new UUID to mount the new clone filesystem. To generate a new UUID for the clone volume, ZFS-LocalPV first replays the xfs log by mounting the device to a tmp localtion.
Here, what is happening is since device creation is slow, so we went ahead and created the tmp location to mount the clone volume but since device has not created yet, the mount failed. In the next try since the tmp …
> fix(xfs, uuid): fixed uuid generation issue when mount fails

- changelogs/unreleased/186-pawanpraka1
- deploy/operators/centos7/zfs-operator.yaml
- deploy/operators/centos8/zfs-operator.yaml
- deploy/yamls/centos7/zfs-driver.yaml
- deploy/yamls/centos8/zfs-driver.yaml
- deploy/yamls/ubuntu/zfs-driver.yaml
- deploy/zfs-operator.yaml
fixes: https://github.com/openebs/zfs-localpv/issues/163
This field was added in Kubernetes 1.16 and it informs Kubernetes about
the volume modes that are supported by the driver. The default is
"Persistent" if it is not used. 
This operator yaml will not work on k8s 1.14 and 1.15, since the driver supports
those k8s version so no need to mention volumeLifecycleModes in the operator as
the default is "Persistent". We broke this in https://github.com/openebs/zfs-localpv/pull/85.
**Checklist:**
> fix(yaml): removing volumeLifecycleModes from the operator yaml

- README.md
As discussed in https://github.com/openebs/zfs-localpv/issues/189, it is possible to use a child dataset instead of the root dataset and this change reflects the usage in readme for users.
> docs ( readme ) Update Readme to specify usage of child dataset for poolname

- changelogs/unreleased/196-pawanpraka1
- pkg/zfs/mount.go
few customers are using old version of the driver where
Status field is not present. So mount will fail after the
upgrade to the 0.9.1 or later version.
Reverting back to the checking if finalizer is set to check if
volume is ready to be mounted.
We need to support upgrade for alpha release until we offically announce it that we no longer support upgrade for alpha release.  
Added this in https://github.com/openebs/zfs-localpv/pull/184
**Checklist:**
> fix(upgrade): Reverting back to old way of checking the volume status

- .travis.yml
- changelogs/unreleased/201-pawanpraka1
CVE-2020-16845 has been reported for go versions earlier to 1.14.7,
this PR upgrades the go version for travis builds.
**Checklist:**
> fix(build): update go version to 1.14.7

- changelogs/unreleased/204-pawanpraka1
- deploy/yamls/ubuntu/zfs-driver.yaml
- deploy/zfs-operator.yaml
fixes : https://github.com/openebs/zfs-localpv/issues/202 and probably https://github.com/openebs/zfs-localpv/issues/72 also.
We are mounting the individual library to run the zfs
binary inside the ZFS-LocalPV daemonset. The problem with this
is each OS has different sets of libraries. We need to have different
Operator yamls for different OS versions.
Here we are mounting the root directory inside the ZFS-LocalPV daemonset Pod
which does chroot to this path and run the command. As all the libraries will
be available which are present on the host inside the Pod, so we don't need to mount each
library here and also it will work for all the Operating systems.
**Any …
> feat(zfspv): mounting the root filesystem to remove the dependency on the Operating system

- .travis.yml
- Makefile
- buildscripts/build.sh
- buildscripts/test-cov.sh
- buildscripts/tools.go
- buildscripts/zfs-driver/entrypoint.sh
- cmd/main.go
- pkg/zfs/mount.go
- upgrade/cleanup.sh
- upgrade/upgrade.sh
Signed-off-by: ajeetrai707 <ajeetrai707@gmail.com>
This PR is to Add license-check for .go , .sh , Dockerfile and Makefile.
This PR check for license for .go , .sh , Dockerfile and Makefile.
If license found then build passes , else build fails.
Command to check license is `make license-check`
**Checklist:**
**PLEASE REMOVE BELOW INFORMATION BEFORE SUBMITTING**
The PR title message must follow …
> Add license-check for .go , .sh , Dockerfile and Makefile

- changelogs/unreleased/221-pawanpraka1
- deploy/yamls/zfsbackup-crd.yaml
- deploy/yamls/zfsrestore-crd.yaml
- deploy/zfs-operator.yaml
- pkg/apis/openebs.io/zfs/v1/zfsbackup.go
- pkg/apis/openebs.io/zfs/v1/zfsrestore.go
- pkg/zfs/zfs_util.go
Added a schema validation for backup and restore CR. Also validating
the server address in the backup/restore controller.
Validating the server address as :
^([0-9]+.[0-9]+.[0-9]+.[0-9]+:[0-9]+)$
which is :
<any number>.<any number>.<any number>.<any number>:<any number>
Here we are validating just the format of the IP, not validating that IP should be
correct which  will be little more complex. In any case if IP is not correct,
the zfs send will fail, so no need to do complex validation to validate the
correct IP and port.
NA
**Checklist:**
> feat(backup,restore): adding validation for backup and restore

- changelogs/unreleased/230-pawanpraka1
- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
For ZFSPV, all the node daemonset pods can go into the terminating state at
the same time since it does not need any minimum availability of those pods.
Changing maxUnavailable to 100% so that K8s can upgrade all the daemonset
pods parallelly. Also added labels to all the pods.
> feat(upgrade): support parallel/faster upgrades for node daemonset

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- Makefile
- Makefile.buildx.mk
- buildscripts/build.sh
- buildscripts/push
- buildscripts/zfs-driver/zfs-driver.Dockerfile
PR add multi arch support for zfs-localpv container images
**Checklist:**
> feat(build): support for multi arch container image

- changelogs/unreleased/234-pawanpraka1
- pkg/driver/controller.go
- pkg/zfs/volume.go
- pkg/zfs/zfs_util.go
add support for creating the Clone from volume as datasource
We can now create the Clone from pvc directly
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-clone
spec:
storageClassName: openebs-clone
dataSource:
name: pvc-vol
kind: PersistentVolumeClaim
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 4Gi 
```
The ZFS_LocalPV driver will create one internal snapshot of the name
same as the new volume name and will create a clone out of it. Also,
while destroying the volume the driver will take care of deleting
the created snapshot for the clone.
**Checklist:**
> feat(clone): add support for creating the Clone from volume as datasource

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
- buildscripts/zfs-driver/zfs-driver.Dockerfile
The RELEASE_TAG and BRANCH env set in actions is not propagated to the buildx container.
- pass RELEASE_TAG and BRANCH as build args to buildkit container
- replace deprecated methods in github actions
**Checklist:**
> fix(build): propagate RELEASE_TAG to buildx container

- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
- This PR changes the zfs-driver quay images to docker hub image.
`quay.io/openebs/zfs-driver:ci` ===> `openebs/zfs-driver:ci`
> chore(yaml): changing the zfs-driver images to multi-arch docker hub images

- pkg/btrfs/btrfs_util.go
- pkg/zfs/zfs_util.go
move btrfs code out of zfs package
**Checklist:**
> chore(refactor): move btrfs code out of zfs package

- deploy/yamls/kustomization.yaml
removing quay from kustomization yaml as we are using multiarch docker images
> fix(kust): removing quay as we are using multiarch docker images

- pkg/driver/controller.go
- pkg/driver/schd_helper.go
- pkg/scheduler/scheduler.go
refactor scheduler for ZFS-LocalPV
**Checklist:**
> chore(refactor): refactor scheduler for ZFS-LocalPV

- buildscripts/zfs-driver/Dockerfile
build is failing on ubuntu 19.10 as the ca-certificate package has been obsolete. Switching to 18.04 as now since we are doing root mount, we can use any ubuntu image.
> feat(image): moving to ubuntu bionic(18.04 LTS) docker image

- buildscripts/zfs-driver/zfs-driver.Dockerfile
- ci/sanity.sh
- pkg/driver/controller.go
flaky sanity fix and updated the docker image to 18.04 for github action, missed adding this in the PR https://github.com/openebs/zfs-localpv/pull/255.
> fix(sanity): fixing flaky sanity test case 

- .github/workflows/chart-lint-test.yml
- .github/workflows/pull_request.yml
- .github/workflows/release-charts.yml
- ct.yaml
This PR adds github action CI for zfs-localpv helm chart lint, test and release.
**Note:** The zfs-localpv helm charts will reside in a directory structure: `deploy/helm`
The following are the details of changes : 
1. Adds `Chart Lint and Test` action to test and lint the chart changes. 
- This action is only triggered if there is any change in the content of `deploy/helm` directory.
2. Modifies the existing `Go` action.
- As a result of the modification, the action will not run for pull requests if there are changes in the `deploy/helm` directory.
3. Adds a `Release Charts` action to release the helm chart. 
- This action triggers only when the push in against `master` and there is a change in the content of …
> feat(helm): add github action for chart test and release

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- changelogs/unreleased/260-pawanpraka1
- pkg/zfs/mount.go
fixing idempotency check for the mount path
For shared mount, the idempotency check was not happening. So checking the mounts for shared volume also.
no
**Checklist:**
> fix(mount): fixing idempotency check for the mount path

- buildscripts/build.sh
- pkg/driver/agent.go
Adding Typecasting as Bsize is different type in different environment
Just adds type cast, It is benign
No
Yes
NA
> Cross Build enviroment bug fixes

- pkg/zfs/mount.go
> fix(mount): creating directory with 0755 permission

- README.md
- deploy/sample/zfssnapclass.yaml
- deploy/sample/zfssnapshot.yaml
- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
- tests/run_test.go
- Bump k8s csi sidecar container image to latest stable releases minimum kubernetes version to support 1.17
- Update the Snapshot specific CRDs to V1 version
The CRDs were taken from https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd
**Checklist:**
> chore(operator): bump k8s csi to latest stable container images

- changelogs/unreleased/266-pawanpraka1
- pkg/driver/schd_helper.go
The ZFS Driver will use capacity scheduler to pick a node
which has less capacity occupied by the volumes. Making this
as default scheduler as it is better than the volume count based
scheduling. We can use below storageclass to specify the scheduler
```yaml
metadata:
parameters:
scheduler: "CapacityWeighted"
```
Please Note that after the upgrade, there will be a change in the behavior.
If we are not using `scheduler` parameter in the storage class then after
the upgrade ZFS Driver will pick the node based on volume capacity weight
instead of the count.
fixes: https://github.com/openebs/zfs-localpv/issues/215
**Explanation**
ZFS Driver …
> feat(schd): adding capacity weighted scheduler

- changelogs/unreleased/281-pawanpraka1
- pkg/driver/agent.go
- pkg/zfs/zfs_util.go
fixes: https://github.com/openebs/zfs-localpv/issues/280
reference: https://github.com/openebs/lvm-localpv/blob/master/pkg/driver/agent.go#L308
> feat(resize): adding resize support for raw block volumes

- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
This PR updates the k8s csi sidecars to gcr for better multi-arch support.
**Checklist:**
> chore(operator): update k8s sidecar images to gcr

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/templates/psp.yaml
- deploy/helm/charts/values.yaml
Add Pod Security policy for zfs localpv charts, disable by default
> refact(charts): add pod security policy for zfslocalpv charts

- changelogs/unreleased/292-pawanpraka1
- deploy/yamls/zfsrestore-crd.yaml
- deploy/zfs-operator.yaml
- pkg/apis/openebs.io/zfs/v1/zfsrestore.go
- pkg/apis/openebs.io/zfs/v1/zz_generated.deepcopy.go
- pkg/builder/restorebuilder/build.go
- pkg/zfs/zfs_util.go
fixes: https://github.com/openebs/zfs-localpv/issues/286
Encrypted pool does not allow the volume to be pre created for the
restore purpose. 
Here changing the design to do the restore first and then create the ZFSVolume object which will bind the volume already created while doing restore. 
Since, the volume gets created while doing the restore, so we need to pass the volume spec and use zfs properties while firing the restore command. Earlier volume was getting created before hand with all the properties so we don't need to pass that while doing the restore. 
PR handles backward compatibility.
> fix(restore): adding support to restore in an encrypted pool

- docs/backup-restore.md
- This PR adds doc update for velero-plugin where newer version of velero-plugin will not work with older zfs-driver versions.
> chore(doc): add prerequisites for using latest velero-plugin

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/crds/zfsrestore.yaml
- deploy/helm/charts/values.yaml
- update chart version
- update README
- update values.yaml
No
**Checklist:**
> [stable/zfs-localpv]: update charts to 1.5.0

- Makefile
- changelogs/unreleased/299-shubham14bajpai
- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/crds/zfsbackup.yaml
- deploy/helm/charts/crds/zfsrestore.yaml
- deploy/helm/charts/crds/zfssnapshot.yaml
- deploy/helm/charts/crds/zfsvolume.yaml
- deploy/helm/charts/templates/csidriver.yaml
- deploy/yamls/zfs-driver.yaml
- deploy/yamls/zfsbackup-crd.yaml
- deploy/yamls/zfsrestore-crd.yaml
- deploy/yamls/zfssnapshot-crd.yaml
- deploy/yamls/zfsvolume-crd.yaml
- deploy/zfs-operator.yaml
With k8s v1.22 the v1beta1 for various resources will no longer be supported. This PR updates the storage and apiexention version to v1.
**Does this PR require any upgrade changes?**: No
Manually verified the control plane upgrade and it works fine.
**Checklist:**
> chore(k8s): updated storage and apiextension version to v1

- changelogs/unreleased/270-pawanpraka1
- deploy/yamls/zfsvolume-crd.yaml
- deploy/zfs-operator.yaml
- go.sum
- pkg/apis/openebs.io/zfs/v1/zfsvolume.go
- pkg/driver/controller.go
- pkg/mgmt/volume/volume.go
- pkg/zfs/volume.go
pvc gets bound even zfs volume creation keeps on failing on the node. 
Currently scheduler returns one node and the provisioner uses that node to provision the volume. Once scheduler returns the node list in the priority order instead of returning just one node, the CSI controller can attempt the volume creation on all the nodes. Here, in this case if the volume is not created, the pvc will not be bound as the controller will wait to the volume to be ready or failed. Also, the the node agent will not reconcile for the creation of the volume, it will attempt to create once and fail if not successful. The csi provisioner will keep on requesting to create the volume in case of failure.
Depends on …
> feat(zfspv): try volume creation on all the nodes

- pkg/mgmt/snapshot/snapshot.go
- pkg/mgmt/volume/volume.go
- pkg/zfs/mount.go
- pkg/zfs/volume.go
fixes: https://github.com/openebs/zfs-localpv/issues/302
User might want to add extra protection on the ZFSVolume CR and wants to add finalizers on it. The current code does not allow the user to setup the user's finalizers on the ZFSVolume CR.
We set the Finalizer to nil while handling the delete event, instead,
we should try to destroy the volume when there are no user finalizers
set. User might have added his own finalizers and we should not try to destroy
the volumes util those user finalizers are removed.
PR handles upgrade scenario.
> feat(zfspv): remove finalizer that is owned by ZFS-LocalPV

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- buildscripts/generate-manifests.sh
This PR
- make use of build and push action in workflow for better multi repo (docker and quay) push support for mulit-arch build
- updates the generated crd changes in helm charts
- adds quay.io repo to push images
- avoids builds when release is create
- adds proper ignore paths for pull requests and builds
quay login details need to be added before merging the PR
**Checklist:**
> refact(actions): use build & push action instead of makefile

- .github/workflows/build.yml
This PR fixes the build workflow criteria. When a PR is merged the `ref` is `remote` instead of `branch`. As we only want to skip the build on release the condition is changed to `!= tag` as tag is only created on release.
Tested this by merging a PR to my local fork repo.
**Checklist:**
> fix(actions): updated the build workflow condition

- changelogs/304-pawanpraka1
- cmd/main.go
- deploy/yamls/zfs-driver.yaml
- deploy/yamls/zfsvolume-crd.yaml
- deploy/zfs-operator.yaml
- docs/faq.md
- pkg/apis/openebs.io/zfs/v1/zfsvolume.go
- pkg/builder/volbuilder/build.go
- pkg/config/config.go
- pkg/driver/agent.go
- pkg/driver/controller.go
- pkg/zfs/volume.go
Here we are setting the node affinity on PV using nodename, so we can not migrate the pods to the new node as k8s scheduler will try to schedule on the old node only.
Here, we can now label the nodes with the unique values using the key `openebs.io/nodeid`. The ZFS LocalPV driver will pick the value from the nodes and set the affinity accordingly.
Now to migrate the PV to the other node, we have to move the disks to the other node and remove the old node from the cluster and set the same label on the new node using the same key and value, which will let k8s scheduler to schedule the pods to the that node.
**Refactoring?**:
We are using nodename as NodeID in code, …
> feat(migration): adding support to migrate the PV to a new node

- pkg/version/version.go
- pkg/zfs/mount.go
Signed-off-by: Nisarg Shah nisshah1499@gmail.com
Resolves potential file inclusion via variable
This is because we are trying to open files using dynamic variables. 
Hence, bad file paths are cleaned using filepath.Clean().
No
N/A
No
**Checklist:**
> Fixes of potential file inclusion via variable

- pkg/driver/controller.go
- pkg/zfs/volume.go
Signed-off-by: Abhinandan-Purkait <abhinandan.purkait@mayadata.io>
- LocalPV ZFS currently does not have any cas-type label to indicate its cas-type.
- This PR adds the cas-type label to the volume attributes. 
**Checklist:**
> Add missing cas-type key for zfs under volume attributes.

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/zfs-contoller.yaml
- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
Set default fstype to ext4 in csi-provisioner. This will be helpful when fsType is not mention in storageclass.
> feat(charts): set default fstype to ext4 in csi-provisioner

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
This PR addresses the issue where a release workflow is triggered when a helm chart is released. The images pushed have tags with the name of the chart like [`zfs-localpv-1.8.1`](https://github.com/openebs/zfs-localpv/actions/runs/939646718) in this case. We should avoid building images in such cases. The if condition added in the workflow prevents such workflows from executing.
**Checklist:**
> fix(actions): skip release workflow on helm release

- pkg/driver/controller.go
fixes: https://github.com/openebs/zfs-localpv/issues/351
The error variable is being redeclared, so this is not
accessible outside of the loop and the provisioner is crashing
while return in case of error as it tries to access err.Error
and err is nil outside of the loop.
The controller will not crash unless there is grpc timeout or controller is not able to provision the volume on any one of the nodes.
no
> fix(crash): reuse the err variable

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/values.yaml
Fix node "name" label declared twice.
See https://github.com/openebs/zfs-localpv/blob/273bf148d460a015f645b26668f3741d0c538675/deploy/helm/charts/templates/_helpers.tpl#L97
Just remove zfsNode.podLabels.name from chart values.
No.
**Checklist:**
> fix(chart): remove zfsNode.podLabels.name from values

- e2e-tests/Dockerfile
- included the dependency package to install opeshift for ansible-modules in e2e-docker file
> included the dependency package to build the e2e image

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
Fixes helm chart description and the badge URL in https://github.com/openebs/zfs-localpv/tree/zfs-localpv-1.3.0/deploy/helm/charts.
**Checklist:**
> refactor: fix helm chart description

- e2e-tests/experiments/functional/backup_and_restore/setup_dependency.yml
- This PR enables the debug log level in velero deployment. It will be helpful in debugging e2e-tests
**Ansible Logs for changes done:**
```
TASK [Get the velero deployment name] ******************************************
task path: /e2e-tests/experiments/functional/backup_and_restore/setup_dependency.yml:34
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl get deploy -n velero -l component=velero -o custom-columns=:.metadata.name --no-headers", "delta": "0:00:01.346005", "end": "2021-07-21 07:59:50.633653", "rc": 0, "start": "2021-07-21 07:59:49.287648", "stderr": "", "stderr_lines": [], "stdout": "velero", "stdout_lines": ["velero"]}
TASK [Patch velero deployment to enable `debug` log-level] *********************
task path: …
```
> refact(e2e): Enable debug log level in velero deployment

- e2e-tests/chaoslib/service_failure/service_chaos.yml
- e2e-tests/experiments/infra-chaos/node_failure/run_e2e_test.yml
- e2e-tests/experiments/infra-chaos/node_failure/test.yml
- e2e-tests/experiments/infra-chaos/node_failure/test_vars.yml
- This PR refactors the node-power failure infra-chaos test. It adds those manual step where we have to load key's passphrase into dataset on the node after node failure cases.
- For docker-restart test-case if we try to stop docker services on node with the command something like: 
` systemctl stop docker.service`
it can give such warning
```
Warning: Stopping docker.service, but it can still be activated by:
docker.socket
```
And then docker services will still be running.
So we can stop docker via socket and can execute following command:
` systemctl stop docker.socket`
> refact(e2e): load key's passphrase in dataset after node-power-failure test case

- deploy/yamls/zfs-driver.yaml
- deploy/zfs-operator.yaml
update zfs operator with custom priorityclass
No
Refer: #363 
**Checklist:**
> refact(operator): update zfs operator with custom priorityclass

- e2e-tests/experiments/upgrade-zfs-localpv/test.yml
- Due to Change in CSI_driver spec, we need to delete csi-driver CR before apply the updated operator yaml, otherwise csi-driver will no get updated as of immutable spec fields. 
```
The CSIDriver "zfs.csi.openebs.io" is invalid: spec.storageCapacity: Invalid value: true: field is immutable
```
> refact(e2e): Cleanup csi-driver CR before applying update operator yaml

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/configmap.yaml
- deploy/helm/charts/values.yaml
Some linux/UNIX distributions, do not follow standard path conventions. The driver currently assumes the zfs binary is in /sbin or /usr/sbin, but on NixOS, for example, it's in /run/current-system/sw/bin.
This adds an option to specify the directory manually. This is dumped into the config map that appears to invoke zfs (you should probably use exec btw)
I don't think so. Sorry I'm not super familiar with helm.
**Any additional information for your reviewer?**
No
> feat(helm): Allow specifying path to zfs binary
